// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { DailyHistory } from "./daily_history_type";
import { CategoryTime } from "./category_time_type";
// Mark import as potentially unused
declare type __keep_CategoryTime = CategoryTime;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `daily_history`.
 *
 * Obtain a handle from the [`dailyHistory`] property on [`RemoteTables`],
 * like `ctx.db.dailyHistory`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.dailyHistory.on_insert(...)`.
 */
export class DailyHistoryTableHandle {
  tableCache: __TableCache<DailyHistory>;

  constructor(tableCache: __TableCache<DailyHistory>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<DailyHistory> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `userId` unique index on the table `daily_history`,
   * which allows point queries on the field of the same name
   * via the [`DailyHistoryUserIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.dailyHistory.userId().find(...)`.
   *
   * Get a handle on the `userId` unique index on the table `daily_history`.
   */
  userId = {
    // Find the subscribed row whose `userId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): DailyHistory | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.userId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: DailyHistory) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DailyHistory) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: DailyHistory) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DailyHistory) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: DailyHistory, newRow: DailyHistory) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: DailyHistory, newRow: DailyHistory) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
