// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { CategoryTime } from "./category_time_type";
// Mark import as potentially unused
declare type __keep_CategoryTime = CategoryTime;


export type User = {
  userId: string,
  email: string | undefined,
  createdAt: __Timestamp,
  lastLoggedIn: __Timestamp,
  points: bigint,
  categories: CategoryTime[],
  lastUpdated: __Timestamp,
  streak: number,
  goals: CategoryTime[],
};
/**
 * An object for generated helper functions.
 */
export const User = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "userId", algebraicType: __AlgebraicTypeValue.String},
        { name: "email", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "lastLoggedIn", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "points", algebraicType: __AlgebraicTypeValue.I64},
        { name: "categories", algebraicType: __AlgebraicTypeValue.Array(CategoryTime.getTypeScriptAlgebraicType())},
        { name: "lastUpdated", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "streak", algebraicType: __AlgebraicTypeValue.U32},
        { name: "goals", algebraicType: __AlgebraicTypeValue.Array(CategoryTime.getTypeScriptAlgebraicType())},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: User): void {
    __AlgebraicTypeValue.serializeValue(writer, User.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): User {
    return __AlgebraicTypeValue.deserializeValue(reader, User.getTypeScriptAlgebraicType());
  },

}

export default User;


